micronaut:
  application:
    name: zup
datasources:
  default:
    url: jdbc:h2:mem:testDb;MODE=Postgresql;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
#    schema-generate: CREATE_DROP
#    dialect: H2
#jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

logger:
  levels:
    io.micronaut.transaction: DEBUG